# -*- coding: utf-8 -*-
import json

with open('src/data/neighbourhoods.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    "kitsilano": {
        "tagline": "Beach town meets bookshop city",
        "personalityDescription": "Kitsilano runs along the water and knows exactly what it is. The seawall is the spine of daily life here \u2014 runners, cyclists, people walking dogs at 7am with coffee in hand. The beach is real and used, the farmers market is genuinely shopped at, and the coffee is taken seriously. There\u2019s money here, but it doesn\u2019t feel cold.\n\nIf your ideal week includes a swim at Kits Pool, a good flat white and a Saturday morning market you actually shop at rather than photograph, this neighbourhood will suit you immediately. It rewards people who want the ocean and the city in the same breath and are willing to pay for the combination.\n\nThe trade-off is cost and transit. Kitsilano is expensive relative to square footage and the bus network is adequate but thin. You\u2019ll want a bike, a car or a high tolerance for the 99 B-Line.",
        "communityQuote": "\u201cI moved here from Toronto thinking I\u2019d stay two years. That was eleven years ago. The seawall gets me every time.\u201d \u2014 a physiotherapist who runs the Kits beach loop most mornings"
    },
    "kerrisdale": {
        "tagline": "Village scale, quiet streets, and very good schools nearby",
        "personalityDescription": "Kerrisdale\u2019s commercial strip on 41st Avenue has the feel of a small-town main street that happens to be in a major city \u2014 family-owned shops that have been there for decades, a reliable bakery, a hardware store that hasn\u2019t been bought out. The residential streets are quiet in a way that takes genuine effort to maintain at this proximity to the city.\n\nFamilies with school-age children, people who have moved through noisier neighbourhoods and want something calmer. Anyone who finds the West End or Commercial Drive exhausting will feel immediately at ease here. Kerrisdale suits people who want to settle, not circulate.\n\nCar-dependent for anything beyond the village strip. Transit runs but infrequently. Low energy \u2014 if you want buzz, you\u2019ll drive to it.",
        "communityQuote": "\u201cI used to think Kerrisdale was boring. Now I have two kids and I understand that I was the problem.\u201d \u2014 a former advertising creative director, now a stay-at-home parent on West Boulevard"
    },
    "marpole": {
        "tagline": "Affordable West Side with a Punjabi-Canadian heartbeat",
        "personalityDescription": "Marpole sits at the south end of Granville Street and operates on its own logic \u2014 more working-class than the neighbourhoods above it, more culturally mixed, more honest about what it is. The Punjabi community has been here for decades and the food reflects it: the best dahl on Granville is not in Yaletown.\n\nPeople priced out of Kerrisdale or Kitsilano who still want West Side access and good transit on the 98 B-Line. Anyone who cares more about the neighbourhood than the postcode. Marpole is for people who want to live well without paying for a name.\n\nLess polished than its neighbours to the north. The Granville corridor gets loud on weekends. Not much evening street life beyond a few strips.",
        "communityQuote": "\u201cI pay half what my friends in Kits pay and I\u2019m a twelve-minute bus ride from downtown. I don\u2019t know what they\u2019re buying that I\u2019m not.\u201d \u2014 a dental hygienist who\u2019s rented on Ash Street for four years"
    },
    "oakridge": {
        "tagline": "Canada Line access, quiet streets, a neighbourhood mid-transformation",
        "personalityDescription": "Oakridge is changing. The Oakridge Centre redevelopment is bringing towers, a new park and a retail centre that will reshape the area over the next several years. Right now it\u2019s a quiet, Canada Line-connected neighbourhood with Langara College nearby and a residential character that hasn\u2019t fully resolved what it\u2019s becoming.\n\nStudents, young professionals who want Canada Line access without paying downtown prices and people comfortable in a neighbourhood actively in transition. The upside of arriving mid-change is that the neighbourhood\u2019s best chapter is still ahead.\n\nThe redevelopment means construction noise and disruption for the foreseeable future. If you need a settled feel immediately, this isn\u2019t the right moment.",
        "communityQuote": "\u201cI moved here for the Canada Line and I stayed because it\u2019s actually pleasant when you get off the main road. The construction will end eventually.\u201d \u2014 a Langara College instructor who rents on West 49th"
    },
    "dunbar": {
        "tagline": "Pacific Spirit Park on the doorstep, quiet enough to hear it",
        "personalityDescription": "Dunbar is where people go when they want the city to leave them alone for a bit. Pacific Spirit Regional Park is walkable \u2014 not a five-minute drive and a parking situation, but genuinely walkable from most Dunbar streets. The commercial strip has been anchored by the same independent businesses for decades.\n\nPeople who work from home and need the walk more than the commute. Families. Anyone for whom silence is a non-negotiable feature of where they live. Most homes here are detached or semi-detached with yards \u2014 space that\u2019s genuinely rare at this price point on the West Side.\n\nGenuinely car-dependent for most things beyond the Dunbar strip. Transit runs, but slowly. The lowest social energy neighbourhood on the Vancouver list \u2014 and that\u2019s the point.",
        "communityQuote": "\u201cI run in Pacific Spirit every morning. I\u2019ve done it for seven years. I still don\u2019t take it for granted.\u201d \u2014 a freelance translator who lives on Dunbar Street"
    },
    "mount-pleasant": {
        "tagline": "Breweries, murals, and a main street that still means something",
        "personalityDescription": "Main Street has pulled off something most commercial corridors can\u2019t manage: it stays useful on a Tuesday. Small restaurants that last more than a season, record shops, studios above garages, a hardware store that hasn\u2019t been converted to condos yet. Mount Pleasant earns its reputation without trying, which is the thing that makes it worth the price.\n\nCreative professionals, people who bike to work, anyone who wants neighbourhood life without the performance of it. The kind of place where the coffee shop remembers your order and the person next to you at the bar is a ceramicist or a sound engineer.\n\nRents have caught up to the reputation. The undiscovered period is definitively over and what\u2019s left is a neighbourhood that\u2019s excellent but no longer cheap.",
        "communityQuote": "\u201cMain Street on a Tuesday afternoon is still the best version of this city I\u2019ve found.\u201d \u2014 a graphic designer who\u2019s lived on Quebec Street for six years"
    },
    "commercial-drive": {
        "tagline": "Three waves of immigration and counting \u2014 still the most itself",
        "personalityDescription": "The Drive has had at least three identities \u2014 Italian, countercultural and whatever it is now \u2014 and none of them fully left. Old espresso bars sit three doors from natural wine shops. The street accumulates history rather than curating it, and the result is a texture that newer neighbourhoods simply can\u2019t manufacture.\n\nSomeone who wants to feel like they live in a city. Who doesn\u2019t mind noise, street chaos or the occasional political leaflet under their wiper. The Drive rewards people who want texture and are happy to be part of it, not just observe it.\n\nNot quiet. Not polished. Parking is essentially impossible and transit is adequate without being excellent. If serenity is what you\u2019re after, look elsewhere.",
        "communityQuote": "\u201cI\u2019ve lived on the Drive for fourteen years. I\u2019ve thought about leaving exactly once, and I came back in the same afternoon.\u201d \u2014 a retired teacher who runs a small zine distro out of her apartment"
    },
    "strathcona": {
        "tagline": "Vancouver\u2019s oldest neighbourhood \u2014 still figuring out what comes next",
        "personalityDescription": "Victorian houses painted unexpected colours, community gardens tucked into vacant lots, and a social infrastructure built by people who chose to stay when staying wasn\u2019t fashionable. Strathcona is Vancouver\u2019s oldest neighbourhood and it carries that layered history visibly \u2014 the Japanese-Canadian block, the Chinese-Canadian block, the artists who arrived in the eighties and never left. Living here feels like being part of something that has actual stakes.\n\nIf you want a neighbourhood with character that took decades to accumulate rather than weeks to brand, this is it. The housing stock is a mix of heritage character homes and newer infill \u2014 many with small yards or garden space, which is rare this close to downtown. The streets are genuinely walked and genuinely used.\n\nThe blocks immediately adjacent to the Downtown Eastside require a comfort with complexity that not everyone has. Safety perception is lower than most of Vancouver and that\u2019s worth taking seriously \u2014 research specific streets before committing.",
        "communityQuote": "\u201cMy house has been in three different hands since 1910. I think about that a lot when I\u2019m in the garden.\u201d \u2014 a furniture maker who bought on Prior Street eight years ago"
    },
    "chinatown": {
        "tagline": "A hundred years of history, a neighbourhood still negotiating its future",
        "personalityDescription": "The Dr. Sun Yat-Sen Classical Chinese Garden sits behind a wall on Carrall Street, completely still. Half a block away, a new speakeasy opens in a space that was a dry goods shop for fifty years. Chinatown holds both of those things simultaneously \u2014 the century-old herbalist and the cocktail bar with no sign on the door \u2014 and the tension between them is what makes it genuinely interesting to live in right now.\n\nPeople who can tolerate a neighbourhood in flux and find that interesting rather than unsettling. The nightlife and restaurant scene here is more adventurous than most newcomers expect \u2014 low-lit rooms, interesting menus, a mix of regulars who know the neighbourhood across its different chapters. Proximity to Strathcona, Main Street and downtown without the cost of any of them.\n\nGrocery options are genuinely limited \u2014 this is a practical consideration worth planning for, not just an atmosphere note. Safety perception is mixed. Gentrification is active and contested here and if that political dimension matters to you in either direction, it\u2019s worth knowing before you arrive.",
        "communityQuote": "\u201cMy family has had a business on Pender Street for forty years. I\u2019ve watched three versions of this neighbourhood. I\u2019m not sure what the fourth one will be.\u201d \u2014 a second-generation herbalist on East Pender"
    },
    "west-end": {
        "tagline": "Dense, walkable, and consistently the most welcoming place in the city",
        "personalityDescription": "Robson, Davie and Denman \u2014 three distinct commercial strips within walking distance of each other and Stanley Park. English Bay beach is at the end of Davie Street, genuinely walkable from anywhere in the neighbourhood. The stretch around Robson and Denman is one of the best concentrations of Asian restaurants in the city \u2014 Japanese, Korean, Chinese and Vietnamese spots that have been earning their regulars for decades. The West End is where the city shows its density working.\n\nPeople who want street life, proximity to everything and don\u2019t need a backyard. The West End has been welcoming to LGBTQ+ residents for decades in a way that feels embedded in the neighbourhood\u2019s identity, not marketed. You\u2019ll feel at home here faster than almost anywhere else on this list.\n\nThe most expensive neighbourhood here for rent and apartments are often older and on the smaller side. Noise from Davie Street on weekends is real \u2014 the further from Davie, the quieter. You\u2019re paying for location and density and the square footage reflects that honestly.",
        "communityQuote": "\u201cI\u2019ve lived in six cities and I\u2019ve never felt at home as fast as I did in the West End. That\u2019s not a small thing.\u201d \u2014 a nurse who moved from Halifax three years ago"
    },
    "riley-park": {
        "tagline": "Farmers market Saturdays, character homes, genuinely neighbourly",
        "personalityDescription": "Riley Park is the neighbourhood that people describe when they say they fell in love with Vancouver. Craftsman houses on leafy streets, the Nat Bailey Stadium on a summer evening, the Hillcrest Community Centre as a genuine social hub. The week here has a rhythm \u2014 morning coffee on the porch, school drop-off, a stop at the farmers market on the way home on Saturday. It\u2019s one of those rare urban neighbourhoods where people actually know their neighbours\u2019 names.\n\nFamilies, people who want stability without sacrificing access to the rest of the city and anyone for whom a backyard matters. The housing stock is predominantly character homes \u2014 many with yards \u2014 and the streets are quiet enough to feel residential without feeling remote. People tend to stay here a long time, which tells you something.\n\nQuieter than most. If you want the city\u2019s energy on a Wednesday night, you\u2019ll have to travel to it.",
        "communityQuote": "\u201cWe moved here for the schools. We stayed because of the block. I didn\u2019t expect that second part.\u201d \u2014 a landscape architect who\u2019s lived on Guelph Street for nine years"
    },
    "yaletown": {
        "tagline": "Converted warehouses, cobblestones, very good restaurants",
        "personalityDescription": "Yaletown pulled off something rare \u2014 industrial bones turned into a neighbourhood that actually works as a neighbourhood. The cobblestone lanes, the loading docks converted to restaurant patios, the seawall two minutes from anywhere. It has the texture that most downtown Vancouver neighbourhoods lack.\n\nPeople who want the city version of low-maintenance. Everything is walkable, everything is available and the streets are clean. Yaletown suits people who work long hours and want their neighbourhood to handle the rest.\n\nExpensive and somewhat homogeneous. You can feel the condo-ness of it after a while. The demographic skews young professional in a way that can feel uniform.",
        "communityQuote": "\u201cI chose Yaletown because I wanted to be able to walk to work and not think about anything else. Three years later, that\u2019s still exactly what I have.\u201d \u2014 a UX director at a Gastown agency"
    },
    "renfrew-collingwood": {
        "tagline": "Vancouver\u2019s most affordable neighbourhood \u2014 and genuinely liveable",
        "personalityDescription": "The Millennium Line SkyTrain runs through it, rents are the lowest in the city proper and the mix of Vietnamese, Chinese and South Asian communities gives the food scene a breadth you won\u2019t find in posher parts of town. This is the neighbourhood that budget-conscious renters find by accident and then stay in.\n\nPeople who need good transit without paying for it twice. Families who need space and aren\u2019t attached to a postcode. The housing here is a mix of older apartments and character homes \u2014 many with yards \u2014 and you get considerably more space for your money than anywhere else in Vancouver.\n\nNo obvious commercial hub and not much street life. It takes time to find the good spots \u2014 they\u2019re not announced. If you need your neighbourhood to have an immediately readable identity, this one takes a few weeks to reveal itself.",
        "communityQuote": "\u201cI pay $1,980 for my one-bedroom and I\u2019m on the Millennium Line. My friends in Kits don\u2019t believe me.\u201d \u2014 a hospital administrator who moved from New Westminster two years ago"
    },
    "lower-lonsdale": {
        "tagline": "SeaBus to downtown, mountains at your back, a waterfront village that earns it",
        "personalityDescription": "The Lonsdale Quay sits at the SeaBus terminal and the view across the water to downtown is genuinely one of the better urban vistas in Metro Vancouver \u2014 visible from the waterfront promenade at any level. The mountains aren\u2019t a backdrop here; they\u2019re accessible. Lower Lonsdale has a thriving craft brewery scene along the waterfront and the Polygon Gallery adds genuine cultural weight to the neighbourhood. It manages to feel like a village and a city at the same time.\n\nPeople who want outdoor access without giving up urban infrastructure. Commuters who don\u2019t mind the SeaBus as a daily ritual tend to say they prefer it to the SkyTrain \u2014 fifteen minutes on the water is a different kind of commute. The North Shore trails and mountains are close in a way that actually changes how you spend your weekends.\n\nThe most expensive GVRD neighbourhood on this list. Once you\u2019re on the North Shore, you\u2019re committed to the crossing \u2014 getting to Vancouver\u2019s east side requires either the SeaBus plus transit or a bridge in traffic. It rewards people who\u2019ve decided the North Shore is home rather than those still testing it.",
        "communityQuote": "\u201cThe SeaBus ride home is the best fifteen minutes of my day. I read, I look at the water, I decompress.\u201d \u2014 a project manager at a downtown architecture firm"
    },
    "deep-cove": {
        "tagline": "End-of-the-road village, a long bus ride from everything",
        "personalityDescription": "Deep Cove is a village at the end of a road into Indian Arm fjord. Kayaks on the water in the morning, Quarry Rock trail above the treeline in the afternoon, and a genuinely unhurried pace that is either exactly what you\u2019re looking for or the clearest possible sign this isn\u2019t your place. It is the least city-like neighbourhood on this list and wears that distinction without apology.\n\nSomeone for whom nature access is the primary reason for living somewhere \u2014 not a priority among several, but the actual reason. Remote workers who genuinely don\u2019t commute. Housing here is predominantly detached houses and townhouses with yards; this isn\u2019t a neighbourhood for someone looking for apartment living. People who live here tend to have made a deliberate choice to slow down and mean it.\n\nA bus does run to Deep Cove but it\u2019s infrequent and the ride is long \u2014 a car is effectively essential for daily life. The village has a handful of caf\u00e9s, a bakery and a kayak rental. If you need more than that within walking distance, this is the wrong fit.",
        "communityQuote": "\u201cI moved here from Yaletown. People thought I was having a breakdown. I\u2019ve never been more okay.\u201d \u2014 a software developer who kayaks before every morning standup"
    },
    "metrotown": {
        "tagline": "The most efficient address in Metro Vancouver \u2014 and genuinely international",
        "personalityDescription": "Metrotown scores a 97 walk score \u2014 higher than most of Vancouver proper \u2014 and the Expo Line SkyTrain is four minutes from almost anywhere in the neighbourhood. But the more interesting thing about Metrotown is what that walkability actually connects you to: Korean grocery stores with ingredients you won\u2019t find elsewhere in the region, Filipino bakeries that have been feeding the same families for thirty years, South Asian sweet shops and Japanese izakayas on the same block. This is one of the most genuinely international neighbourhoods in Metro Vancouver and the food reflects that without making a fuss about it.\n\nPeople who want maximum city function at below-Vancouver prices and are comfortable in a dense, tower-heavy environment. The daily rhythm here is efficient \u2014 transit is fast, errands are walkable and the variety of food and retail within a ten-minute walk is genuinely hard to beat. If you find that kind of density energising rather than overwhelming, Metrotown delivers.\n\nHigh-rise tower living is the dominant housing form and green space is limited. Noise and traffic are constants. This is a neighbourhood built around infrastructure and if that\u2019s not your idea of home, it\u2019ll feel like it from the first week.",
        "communityQuote": "\u201cI have three Korean grocery stores, two Filipino bakeries and a SkyTrain stop within a five-minute walk. I do not miss paying Vancouver rent.\u201d \u2014 an accountant who moved from Kitsilano two years ago"
    },
    "burnaby-heights": {
        "tagline": "Italian heritage, leafy streets, and a strip that predates the word \u2018curated\u2019",
        "personalityDescription": "The commercial strip on Hastings Street has an Italian-heritage backbone \u2014 bakeries, a deli, a Portuguese chicken spot \u2014 alongside the kind of hardware store and dry cleaner that disappeared from most Vancouver neighbourhoods a decade ago. Behind the strip, the residential streets are quiet and tree-lined, with a mix of older apartments and character homes that give the neighbourhood a genuinely settled feel.\n\nPeople who want neighbourhood character without paying to be fashionable. Families who need space. The pace here is unhurried in the best way \u2014 locals know each other, the strip is genuinely used rather than photographed and the week has a comfortable rhythm that doesn\u2019t require the city to perform for you.\n\nThe Hastings strip is reliable but not extensive \u2014 you\u2019ll know everything it offers within the first month. Transit runs but it\u2019s not SkyTrain-convenient for downtown commutes.",
        "communityQuote": "\u201cI buy my bread at the same bakery my landlord\u2019s mother used to go to. That\u2019s not nothing.\u201d \u2014 a carpenter who rents on Dundas Street"
    },
    "port-moody": {
        "tagline": "Burrard Inlet, craft beer, SkyTrain and actual hiking trails",
        "personalityDescription": "Port Moody has more craft breweries per capita than almost anywhere in BC and they sit along the inlet within walking distance of Rocky Point Park and the Evergreen SkyTrain. It\u2019s a small city that has figured out its identity \u2014 outdoorsy during the week and a bit boisterous on Friday evenings, with the mountains and the water always in the frame.\n\nLiving here has a specific rhythm: trails before work, coffee at the local roaster, the occasional pint at the brewery end of Murray Street on a Thursday. It suits people who want outdoor access and a social scene that doesn\u2019t require going into Vancouver \u2014 and who find the commute a fair trade for everything else. Families are well-represented and the community feel is genuine rather than aspirational.\n\nAt the end of the Evergreen Extension, commuting into downtown Vancouver takes 40-50 minutes by SkyTrain. If you\u2019re in the city every day, that\u2019s the negotiation you\u2019ll make with this neighbourhood every morning \u2014 most people who\u2019ve done it say it\u2019s worth it.",
        "communityQuote": "\u201cI trail run before work three mornings a week and I\u2019m at my Gastown office in 45 minutes.\u201d \u2014 an environmental engineer who bought a townhouse near Moody Centre"
    },
    "maillardville": {
        "tagline": "French-Canadian heritage west of the Rockies, and genuinely affordable",
        "personalityDescription": "The oldest French-Canadian settlement west of Manitoba \u2014 a fact that sounds like a tourism board line until you see the Place Maillardville square and the heritage buildings that survived suburban expansion by being genuinely worth keeping. It\u2019s a quiet working neighbourhood with Coquitlam Centre SkyTrain nearby and a sense of place that most Metro Vancouver suburbs conspicuously lack.\n\nPeople who care about neighbourhood history and want somewhere that has an identity beyond its transit connections. Budget-conscious renters who want SkyTrain access without paying Vancouver prices. The pace here is calm and residential \u2014 yards are common and the community tends toward the long-established rather than the newly arrived.\n\nLimited food and retail options beyond the basics \u2014 this is a neighbourhood you live in rather than visit and the distinction matters if you need ongoing novelty from your surroundings. The French-Canadian heritage is present but subtle; it\u2019s not a cultural quarter in any obvious sense.",
        "communityQuote": "\u201cMost people in Coquitlam have never heard of Maillardville. I find that useful.\u201d \u2014 a librarian who\u2019s rented here for three years"
    },
    "steveston": {
        "tagline": "Historic fishing village, working harbour, a pace that gives you room to breathe",
        "personalityDescription": "Steveston is Richmond\u2019s anomaly \u2014 a working harbour with fishing boats that actually fish, independent shops that predate the internet and a Japanese-Canadian community whose history runs deep in the neighbourhood\u2019s fabric. The waterfront path is used by locals as much as visitors and the Saturday market is the real kind.\n\nThe pace here is genuinely slow in the way that some people find liberating. Neighbours know each other, the community league is active and the week has the kind of unhurried rhythm that\u2019s hard to find anywhere else at this price point in Metro Vancouver. Housing is predominantly single-family homes and townhouses with yards \u2014 space that\u2019s rare this close to the water.\n\nFar from downtown Vancouver \u2014 45-60 minutes by transit \u2014 and a car is practically necessary for daily life. The village is small enough that you\u2019ll exhaust its options if you\u2019re used to urban density. This is a feature if you\u2019ve chosen it deliberately.",
        "communityQuote": "\u201cI can walk to the harbour at 6am and watch the fishing boats come in. I\u2019ve lived here four years and I still don\u2019t take it for granted.\u201d \u2014 a retired teacher who moved from East Vancouver"
    },
    "cloverdale": {
        "tagline": "A small town that survived becoming a suburb by staying itself",
        "personalityDescription": "Cloverdale is the historic heart of what became Surrey \u2014 brick storefronts from the 1800s, a rodeo ground and a main street that still functions as one. The municipal centre long since moved elsewhere, which means Cloverdale has been left to operate as its own distinct small town within a larger city. That\u2019s not a consolation prize; it\u2019s what gives it character that most of Surrey doesn\u2019t have.\n\nThe pace is unhurried and the community is established \u2014 people here tend to know their neighbours, have yards and take the local seriously. It\u2019s a good fit for people who want space and genuine affordability and aren\u2019t measuring their life against the city.\n\nCar-essential for almost everything and the commute to downtown Vancouver is an hour each way. This is the honest trade-off and it\u2019s a real one \u2014 Cloverdale makes sense for people who have made their peace with it.",
        "communityQuote": "\u201cI pay $1,750 for a two-bedroom. In Vancouver that doesn\u2019t exist. I drive 45 minutes to work. It\u2019s a fair trade.\u201d \u2014 an electrician who moved from New Westminster"
    },
    "surrey-city-centre": {
        "tagline": "SkyTrain-adjacent, most affordable on the list, mid-transformation",
        "personalityDescription": "Surrey City Centre is a neighbourhood investing in itself. The King George SkyTrain station anchors an area that city planners envision as Metro Vancouver\u2019s second downtown \u2014 towers going up, a new library, an arts centre and a university campus already in place. Right now it sits somewhere between intention and arrival, which makes it genuinely interesting if you can tolerate a neighbourhood still finding its footing.\n\nDaily life here has the energy of somewhere mid-change: new businesses opening alongside established ones, a highly diverse population that makes the food scene punchy and unpredictable and a SkyTrain connection that makes the rest of the region accessible without a car. For the right person \u2014 early in a career, new to Canada or simply practical about budget \u2014 this neighbourhood offers real value that the more established areas can\u2019t match.\n\nSafety perception varies significantly street by street and that\u2019s worth taking seriously. Research specific blocks before committing \u2014 the gap between the neighbourhood\u2019s best and most challenging areas is wider here than anywhere else on this list.",
        "communityQuote": "\u201cPeople act like I made a compromise moving here. I have a SkyTrain stop, a great Filipino restaurant and I pay $1,750 a month. That\u2019s not a compromise.\u201d \u2014 a nursing student at SFU Surrey"
    },
    "sapperton": {
        "tagline": "Heritage streets, big yards and the transit paradox that works in your favour",
        "personalityDescription": "Sapperton is a quiet, residential corner of New Westminster with a surprising amount of heritage housing stock \u2014 older character homes on generous lots, many with yards that would cost twice as much anywhere closer to Vancouver. The Royal Columbian Hospital anchors one end of the neighbourhood and a small but solid craft beer strip on Braid Street adds some evening life. The week here is calm and domestic in the best sense.\n\nThe curious thing about Sapperton is its transit paradox: a walk score of 26 (daily errands require a car) alongside a transit score of 75 (getting to downtown Vancouver by SkyTrain is genuinely easy). If you commute by transit and are happy to drive for groceries, this works well. If walkable errands matter as much as the commute, it\u2019s a harder fit.\n\nNot much within walking distance beyond the immediate neighbourhood. The craft beer strip is worth knowing but narrow. Sapperton suits people who want a quiet residential base with a reliable commute more than an activated neighbourhood streetscape.",
        "communityQuote": "\u201cI take the SkyTrain to downtown Vancouver in 25 minutes. Then I drive to the grocery store. That\u2019s Sapperton.\u201d \u2014 a lab technician at Royal Columbian"
    },
    "fort-langley": {
        "tagline": "1800s heritage village, one of a kind, genuinely far from everything",
        "personalityDescription": "Fort Langley looks like what Vancouver neighbourhoods aspire to be \u2014 brick storefronts from the 1800s, a Hudson\u2019s Bay fort that\u2019s now a national historic site and a Saturday market that people drive an hour to attend. But what makes it worth considering as a place to live rather than just visit is what it feels like the rest of the week: quiet streets, real yards, a community league that functions and a river trail that goes somewhere meaningful.\n\nLife here runs on seasons and the village rhythm \u2014 the market fills up in summer, the trails are busy on autumn weekends and the community tends toward people who chose this deliberately and stayed. Residents have typically been here a long time. Housing is almost entirely detached homes and townhouses with proper outdoor space.\n\n50-60 minutes to downtown Vancouver by car on a reasonable day and transit is not a practical commuting option. This neighbourhood makes sense for remote workers and people who have genuinely decided the city is behind them \u2014 not people testing the idea.",
        "communityQuote": "\u201cI moved here from Yaletown five years ago. I have never once thought about going back.\u201d \u2014 a copywriter who works remotely and runs the river trail on weekday mornings"
    },
    "white-rock": {
        "tagline": "Beachfront promenade, seaside town scale, a long way south",
        "personalityDescription": "White Rock has a promenade, a pier and a beach that gets genuinely warm in August. The town above the hill operates at a pace that\u2019s deliberately slower than the rest of Metro Vancouver \u2014 unhurried, neighbourly and oriented around the water and the week\u2019s small rituals rather than the city\u2019s agenda. The demographic skews toward people who have made their peace with slowing down: retirees, remote workers and families who want outdoor space and a community that actually shows up for each other.\n\nIf the idea of walking the pier on a Tuesday morning before work \u2014 or instead of it \u2014 resonates, White Rock is worth serious consideration. Housing here is predominantly detached homes and townhouses with yards. The town feels genuinely like a place rather than a suburb.\n\nAn hour minimum to downtown Vancouver \u2014 plan on it and decide if the trade-off works before you sign anything. Summers bring day-trippers to the waterfront and the town gets busier than its year-round character suggests. Winters are quiet in a way that suits some people and doesn\u2019t suit others.",
        "communityQuote": "\u201cI walk the pier every morning at 7am. In eight years I\u2019ve missed maybe twenty days. That\u2019s why I\u2019m here.\u201d \u2014 a retired teacher who moved from Burnaby"
    }
}

updated = 0
not_found = []

for entry in data:
    nid = entry.get('id')
    if nid in updates:
        entry['tagline'] = updates[nid]['tagline']
        entry['personalityDescription'] = updates[nid]['personalityDescription']
        entry['communityQuote'] = updates[nid]['communityQuote']
        updated += 1
    else:
        not_found.append(nid)

with open('src/data/neighbourhoods.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated: {updated} entries")
print(f"IDs in JSON not in update map: {not_found}")
